title: Marcos Esparza 
logo: /assets/img/LinkedIn Profile Pic.PNG
description: Mechanical engineering student from the Permian Basin interested in energy systems, thermo-fluids, piping, experimental testing, and hands-on work in rocketry.
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
sass:
  style: compressed
